name: Build EXE for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller main.py --onefile --name CyberRaid

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: CyberRaid-Windows
          path: dist/CyberRaid.exe
